
tabPanel_overlap <- tabPanel("Overlap",
                             fluidRow(
                               useShinyjs(),
                               extendShinyjs(script  = "./www/enrichr.js"),
                               column(width=12, p('')),
                               column(width=12, 
                                      wellPanel(h3("Cutoff Setting"), 
                                                numericInput("fdr", "FDR Cutoff:",
                                                            min = 0, max = 1, 
                                                            value = .05, step = .0001),
                                                uiOutput('showMethodBox'),
                                                actionButton("showRes","Show Result"))),
                               
                               column(width=12, p('')),
                               column(width=6, plotOutput('figure_UP')),
                               column(width=6, plotOutput('figure_DN')),
                               column(width=12, p('')),
                               
                               column(width=2, 
                                      wellPanel(h3("Heatmap Setting"), 
                                                checkboxInput("heat_unsup",
                                                              label = "Plot Unsupervised Heatmap",
                                                              value = TRUE),
                                                numericInput(inputId = "heat_NoSampleCl",
                                                             label = "NO. Sample Clusters Label",
                                                             value = 2, min = 1, max = 10),
                                                numericInput(inputId = "heat_NoGeneCl",
                                                             label = "NO. Gene Clusters Label",
                                                             value = 2, min = 1, max = 100),
                                                sliderInput("heat_x", "Heatmap Width:",
                                                            min = 100, max = 1000, 
                                                            value = 500, step = 10),
                                                sliderInput("heat_y", "Heatmap Height:",
                                                            min = 100, max = 1000, 
                                                            value = 500, step = 10),
                                                sliderInput("xmar", "X Axis Margin:",
                                                            min = 0, max = 100, 
                                                            value = 5, step = 1),
                                                sliderInput("ymar", "Y Axis Margin:",
                                                            min = 0, max = 100, 
                                                            value = 5, step = 1),
                                                textInput(inputId = "heat_title",
                                                          label = "Heatmap Title",
                                                          value = ""),
                                                actionButton("showHeatmap","Show Heatmap"))),
                               column(width=10, plotOutput('de_heatmap')),
                               
                               column(width=12, p('')),
                               column(width=12, p('')),
                               column(width=12, p('')),
                               column(width=12, p('')),
                               column(width=12, p('')),
                               column(width=12, p('')),
                               column(width=12, p('')),
                               column(width=12, p('')),
                               
                               column(width = 12,
                                      wellPanel(h3("Output Setting"),
                                                conditionalPanel('input.showRes',
                                                                 uiOutput('showInterTableBox'),
                                                                 actionButton("showResTable","Show Result Table"),
                                                                 actionButton("goAnalyze","Finalize as DE Genes!"),
                                                                 # downloadButton('downloadExcel', 'Download as Excel'),
                                                                 downloadButton('downloadCSV', 'Download as CSV'),
                                                                 downloadButton('downloadTXT', 'Download as TXT')))),
                               column(width=12, dataTableOutput('interTableRes'))
                             )
)

